# Generated by Django 4.2.3 on 2024-02-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=100)),
                ('coordinate', models.CharField(max_length=100)),
                ('temp', models.CharField(max_length=100)),
                ('pressure', models.CharField(max_length=100)),
                ('humidity', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
